#Available languages: de_De, en_US, fr_FR, it_IT, ru_RU es_ES.


language: en_US

#Set this to the world that is used where the plots are, used in case you use multiverse core
plot_world: world






